Algoritmo "Verificador de intervalos positivos"

Var
   num1: inteiro
Inicio
   escreval("Digite um numero")
   leia (num1)
   se (num1 >= 10) e (num1 <= 20) entao
      escreval ("O numero esta no intervalo de 10 a 20, bao dms")
   fimse
   se (num1 > 50) entao
      escreval("O numero é maior que 50, calma lá tbm né")
   fimse
   se (num1 < 10) entao
      escreval ("o numero nao atende os criterios, fazueli")
   fimse
Fimalgoritmo